package com.cylan.jiafeigou.cache.db.module;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cylan.jiafeigou.cache.db.module.Account;
import com.cylan.jiafeigou.cache.db.module.Device;
import com.cylan.jiafeigou.cache.db.module.DownloadFile;
import com.cylan.jiafeigou.cache.db.module.DPEntity;
import com.cylan.jiafeigou.cache.db.module.FeedBackBean;
import com.cylan.jiafeigou.cache.db.module.FriendBean;
import com.cylan.jiafeigou.cache.db.module.FriendsReqBean;
import com.cylan.jiafeigou.cache.db.module.HistoryFile;
import com.cylan.jiafeigou.cache.db.module.SysMsgBean;

import com.cylan.jiafeigou.cache.db.module.AccountDao;
import com.cylan.jiafeigou.cache.db.module.DeviceDao;
import com.cylan.jiafeigou.cache.db.module.DownloadFileDao;
import com.cylan.jiafeigou.cache.db.module.DPEntityDao;
import com.cylan.jiafeigou.cache.db.module.FeedBackBeanDao;
import com.cylan.jiafeigou.cache.db.module.FriendBeanDao;
import com.cylan.jiafeigou.cache.db.module.FriendsReqBeanDao;
import com.cylan.jiafeigou.cache.db.module.HistoryFileDao;
import com.cylan.jiafeigou.cache.db.module.SysMsgBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig downloadFileDaoConfig;
    private final DaoConfig dPEntityDaoConfig;
    private final DaoConfig feedBackBeanDaoConfig;
    private final DaoConfig friendBeanDaoConfig;
    private final DaoConfig friendsReqBeanDaoConfig;
    private final DaoConfig historyFileDaoConfig;
    private final DaoConfig sysMsgBeanDaoConfig;

    private final AccountDao accountDao;
    private final DeviceDao deviceDao;
    private final DownloadFileDao downloadFileDao;
    private final DPEntityDao dPEntityDao;
    private final FeedBackBeanDao feedBackBeanDao;
    private final FriendBeanDao friendBeanDao;
    private final FriendsReqBeanDao friendsReqBeanDao;
    private final HistoryFileDao historyFileDao;
    private final SysMsgBeanDao sysMsgBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        downloadFileDaoConfig = daoConfigMap.get(DownloadFileDao.class).clone();
        downloadFileDaoConfig.initIdentityScope(type);

        dPEntityDaoConfig = daoConfigMap.get(DPEntityDao.class).clone();
        dPEntityDaoConfig.initIdentityScope(type);

        feedBackBeanDaoConfig = daoConfigMap.get(FeedBackBeanDao.class).clone();
        feedBackBeanDaoConfig.initIdentityScope(type);

        friendBeanDaoConfig = daoConfigMap.get(FriendBeanDao.class).clone();
        friendBeanDaoConfig.initIdentityScope(type);

        friendsReqBeanDaoConfig = daoConfigMap.get(FriendsReqBeanDao.class).clone();
        friendsReqBeanDaoConfig.initIdentityScope(type);

        historyFileDaoConfig = daoConfigMap.get(HistoryFileDao.class).clone();
        historyFileDaoConfig.initIdentityScope(type);

        sysMsgBeanDaoConfig = daoConfigMap.get(SysMsgBeanDao.class).clone();
        sysMsgBeanDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        downloadFileDao = new DownloadFileDao(downloadFileDaoConfig, this);
        dPEntityDao = new DPEntityDao(dPEntityDaoConfig, this);
        feedBackBeanDao = new FeedBackBeanDao(feedBackBeanDaoConfig, this);
        friendBeanDao = new FriendBeanDao(friendBeanDaoConfig, this);
        friendsReqBeanDao = new FriendsReqBeanDao(friendsReqBeanDaoConfig, this);
        historyFileDao = new HistoryFileDao(historyFileDaoConfig, this);
        sysMsgBeanDao = new SysMsgBeanDao(sysMsgBeanDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Device.class, deviceDao);
        registerDao(DownloadFile.class, downloadFileDao);
        registerDao(DPEntity.class, dPEntityDao);
        registerDao(FeedBackBean.class, feedBackBeanDao);
        registerDao(FriendBean.class, friendBeanDao);
        registerDao(FriendsReqBean.class, friendsReqBeanDao);
        registerDao(HistoryFile.class, historyFileDao);
        registerDao(SysMsgBean.class, sysMsgBeanDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        downloadFileDaoConfig.clearIdentityScope();
        dPEntityDaoConfig.clearIdentityScope();
        feedBackBeanDaoConfig.clearIdentityScope();
        friendBeanDaoConfig.clearIdentityScope();
        friendsReqBeanDaoConfig.clearIdentityScope();
        historyFileDaoConfig.clearIdentityScope();
        sysMsgBeanDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public DownloadFileDao getDownloadFileDao() {
        return downloadFileDao;
    }

    public DPEntityDao getDPEntityDao() {
        return dPEntityDao;
    }

    public FeedBackBeanDao getFeedBackBeanDao() {
        return feedBackBeanDao;
    }

    public FriendBeanDao getFriendBeanDao() {
        return friendBeanDao;
    }

    public FriendsReqBeanDao getFriendsReqBeanDao() {
        return friendsReqBeanDao;
    }

    public HistoryFileDao getHistoryFileDao() {
        return historyFileDao;
    }

    public SysMsgBeanDao getSysMsgBeanDao() {
        return sysMsgBeanDao;
    }

}
